#Star Project
print("Star Project")
name = input("Enter Your Name : ")
how = input("And how much Star you Need : ")
funt = name.center(len(name) + int(how)*2,"*")
print(funt)
Exit = input("Enter you Name and Press Enter : ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                         BYE                  ")
print("                        ENJOY                 ")